channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  # mediapipe supports Python3.7-3.10
  - python=3.10
  - pip:
    - fastapi
    - torch
    - mediapipe
